# main text of home
name: HanXiao Li
bio: 

# twitter summary info
description: A blog about technology and stuff related

picture: assets/images/picture.png

url: http://koppl.in/violet
# your url: http://USERNAME.github.io

markdown: kramdown
highlighter: rouge

# if you don't have any of social below, comment the line
facebook: profile.php?id=100010212194875
twitter: moyucanchi
github: moyucanchi
email: moyucanchi@gmail.com

sass:
  sass_dir: _sass
  style: :compressed

gems:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, indigo-gh-pages.zip, Rakefile, screen-shot.png, travis.sh, tasks]
